<!DOCTYPE html>
<html>
	<head>
        <title>Barbers</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta charset="utf-8">
        <link rel="stylesheet" href="style.css" type="text/css">
		<script type="text/javascript" src="js.js"></script>
    </head>
	<body>		
 			<aside id="sidebar">
				<div id="logo">
					<img alt="Barbers" src="img/logo.png">
				</div>
				<div id="menu">
					<div class="line_top"><img src="img/line_t.png" /></div>
						<nav>
							<a href="">
								<span>Главная</span>
							</a><br>
							<a href="">
								<span>Конкурсы</span>
							</a><br>
							<a href="">
								<span>Прайс</span>
							</a><br>
							<a href="">
								<span>Мы в соц сетях</span>
							</a><br>
							<a href="">
								<span>Контакты</span>
							</a>
						</nav>
					<div class="line_bottom"><img src="img/line_b.png" /></div>
				</div>
				<div id="social">
					<a class="twitter" href=""></a><br>
					<a class="facebook" href=""></a><br>
					<a class="odnoklassniki" href=""></a><br>
					<a class="vkontakte" href=""></a><br>
				</div>
				<div class="low">
					<p id="created">created by</p><br>
					<p id="name">Dmitry Yakovlev</p>
				</div>
			</aside>
			<div class="main">
				<a class="img_middle" href="/">
				</a>
				
				<a class="img_top" href="/">
					
				</a>
					
				<a class="img_left" href="/">
					
				</a>
				<a class="img_rigth" href="/">
						
				</a>
			</div>
		